FROM artilleryio/artillery:latest
ENV NODE_ENV=production

RUN mkdir /app 
WORKDIR /app
COPY ["package.json", "package-lock.json*", "babel.config.json", "performanceTests", "src", "test", "/app/"]
RUN npm install --production --silent && mv node_modules ../
COPY . .
RUN chown -R node /app
USER node
ENTRYPOINT ["npm", "run", "docker"]
CMD [ "" ]